### ISSUE TITLE
Code enhancement

### ISSUE THREAD

**Issue by pquintens** [fra589/grbl-Mega-5X#126]
Hello,
I'm not a programming expert but I was wondering if the following code made sense

**Config.h**
…
**#define AXIS_1_NAME 'X'** // Axis names must be in X, Y, Z, A, B, C, U, V & W.
**#define AXIS_2_NAME 'Y'**
**#define AXIS_3_NAME 'Z'**
…

**Main.c**
…
int main(void)
{
  // Initialize system upon power-up.
  serial_init();   // Setup serial baud rate and interrupts
  settings_init(); // Load Grbl settings from EEPROM
  stepper_init();  // Configure stepper pins and interrupt timers
  system_init();   // Configure pinout pins and pin-change interrupt

  // Initialize axis mask bits (ability to axis renaming and cloning)
  // and global table of axis names.

  **if (AXIS_1_NAME == 'X') { // will be always true**
    axis_X_mask |= (1<<AXIS_1);
    axis_name[0] = 'X';
  }
  **if (AXIS_2_NAME == 'X') { // will never be true**
    axis_X_mask |= (1<<AXIS_2);
    axis_name[1] = 'X';
  }
  **if (AXIS_3_NAME == 'X') { // will never be true**
    axis_X_mask |= (1<<AXIS_3);
    axis_name[2] = 'X';
  }
…
  **if (AXIS_1_NAME == 'Y') { // will never be true**
    axis_Y_mask |= (1<<AXIS_1);
    axis_name[0] = 'Y';
  }
  **if (AXIS_2_NAME == 'Y') { // will be always true**
    axis_Y_mask |= (1<<AXIS_2);
    axis_name[1] = 'Y';
  }
  **if (AXIS_3_NAME == 'Y') { // will never be true**
    axis_Y_mask |= (1<<AXIS_3);
    axis_name[2] = 'Y';
  }
…

This is also repeated in gcode.c file
Cordialement,

**Comment by fra589** [comment]
Hi @pquintens,  
  
Attention, the tests that you mention are "always true" or "always false" only according to the definition "`#define`" of the name of the axes. If we change these definitions, it will no longer be the same tests which will be "always true" or "always false"  
  
At the beginning of the writing of the code allowing to modify the name of the different axes, I thought of using a new run time parammeter. This is why I wrote the runtime tests in main.c and gcode.c.  
Then, for various reasons, I did not write the code for this dynamic axis name parameter, but I used a compile time definition for the name of the axes.  
By keeping the runtime tests on the name of the axes, it's still possible to complete the code to define the axes at runtime, but you're right, the code could also be optimized by using compile time tests (`#if` instead of `if`) in main.c and gcode.c.  
  
@++;  
Gauthier.
