### ISSUE TITLE
5th Axis Issue - Fixed

### ISSUE THREAD

**Issue by liushuya7** [fra589/grbl-Mega-5X#13]
Hi Gauthier,

Whenever I jog or send Gcode commands to move the 5th axis (only the 5th axis has this issue), the grbl-Mega-5X always froze. I have to reset to make it work again. Have anyone ever encountered similiar problems? I checked all my wire connections, there was no problem. I suppose something within the grbl-Mega-5X firmware is not functioning correctly? Please provide some help. Thank you!

Joshua

**Comment by liushuya7** [comment]
I reloaded GRBL into Arduino. Problem solved. Please discard this issue. Thx.

**Comment by fra589** [comment]
Hi Joshua,

I already have this type of bug... 

With many tests loading and reloading Grbl onto the Arduino, sometime, there is memory corrupt that need another reload for correct it.  
  
Some other times, when you change the number of axis or the axis names or the axis positions, you need to reset the parameters eeprom memory to "factory profile" (see Grbl command [`$RST=*`](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands)) because the number of parameters is not the same from the anterior version to the new one, so the eeprom mapping is not the same.  
  
However, you had the right reflex to reload Grbl on your Ardiono board 😃   
  
@++;  
Gauthier.
