### ISSUE TITLE
Can anyone add backlash comp. 

### ISSUE THREAD

**Issue by arlimbad222** [fra589/grbl-Mega-5X#136]
Hello I use grbl 5x for long time now . I use delrin nut on my milling. now the main issue for me is backlash. each nut has a backlash about 0.03mm can anyone help me out of that problem thankyou so much.

**Comment by fra589** [comment]
Hi @arlimbad222,  
This have been already asked here: https://github.com/fra589/grbl-Mega-5X/issues/40  
It's already on (long) TODO list...  
Be patient, since I plan to use Grbl on my old weared lathe, I will probably need this feature in a while  😄.  
Watch for the https://github.com/fra589/grbl-Mega-5X/issues/40 evolutions.
@++;
Gauthier.
