### ISSUE TITLE
Stepper Motor not moving, Clicking/Ticking, 0.5s Intervals of locked and unlocked

### ISSUE THREAD

**Issue by NilsNippe** [fra589/grbl-Mega-5X#169]
Hi,
I am using a ramps 1.4 board with an anrduino mega2560, with a dual Y-axis.
I can't get my motors to move (whilst homing), they just rock back and forth (maybe one step forwards, one step backwards? -> [Video1 ](https://user-images.githubusercontent.com/50922230/104066142-2be7f980-5201-11eb-982f-ee8d8caddbe4.mp4)& [Video2](https://user-images.githubusercontent.com/50922230/104066145-2d192680-5201-11eb-8f84-90d72c7cca29.mp4) attached).
When moving an axis in this state, it oscillates between having a bit of resistance (more resistance than when completely turned off) and being impossible to move (-> [Video3 ](https://user-images.githubusercontent.com/50922230/104066146-2e4a5380-5201-11eb-8300-c306318d55ee.mp4)attached).
My Configuration:

$0 = 10    (Step pulse time, microseconds)
$1 = 25    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 0    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 3    (Status report options, mask)
$11 = 0.010    (Junction deviation, millimeters)
$12 = 10.000    (Arc tolerance, millimeters)
$13 = 0    (Report in inches, boolean)
$20 = 1    (Soft limits enable, boolean)
$21 = 1    (Hard limits enable, boolean)
$22 = 1    (Homing cycle enable, boolean)
$23 = 0    (Homing direction invert, mask)
$24 = 60.000    (Homing locate feed rate, mm/min)
$25 = 20.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 2.000    (Homing switch pull-off distance, millimeters)
$30 = 1000    (Maximum spindle speed, RPM)
$31 = 0    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 71.000    (X-axis travel resolution, step/mm)
$101 = 71.000    (Y-axis travel resolution, step/mm)
$102 = 71.000    (Z-axis travel resolution, step/mm)
$103 = 71.000   
$110 = 500.000    (X-axis maximum rate, mm/min)
$111 = 500.000    (Y-axis maximum rate, mm/min)
$112 = 5.000    (Z-axis maximum rate, mm/min)
$113 = 500.000   
$120 = 10.000    (X-axis acceleration, mm/sec^2)
$121 = 10.000    (Y-axis acceleration, mm/sec^2)
$122 = 10.000    (Z-axis acceleration, mm/sec^2)
$123 = 10.000   
$130 = 200.000    (X-axis maximum travel, millimeters)
$131 = 200.000    (Y-axis maximum travel, millimeters)
$132 = 50.000    (Z-axis maximum travel, millimeters)
$133 = 200.000

The step pulse seems fine lenght-wise, but has quite a low amplitude (0.3V vs 5V without stepper driver inserted, ->Image1 attached)
The phases of being movable/not movable are accompanied by interference (->Image2 attached).

I am not sure what could cause this problem, as the stepper drivers are functional and the settings are as close to reasonable as i can get them without actually having the motors move.

[Image2-Interference](https://user-images.githubusercontent.com/50922230/104065862-bda33700-5200-11eb-840c-5d329b9d10e7.jpg)
[Image3-multiplePulses](https://user-images.githubusercontent.com/50922230/104065865-be3bcd80-5200-11eb-80d8-3a9488a01310.jpg)
[Image1-singlePulse](https://user-images.githubusercontent.com/50922230/104065867-bed46400-5200-11eb-8fbf-962773c8a394.jpg)

**Comment by fra589** [comment]
Hi @NilsNippe,  
  
I don't really see where this behavior can come from either...  
I never seen this behavior before when developping and testing grbl-Mega-5X.  
- Unpredictable behaviors can happen when the configuration EEPROM is corrupted (this happens when testing different versions of Grbl or different axis configurations) in this case the command Grbl `$RST=*` restores the default parameters of the program and everything back to normal,  
 - Behavior resembling this could come from a bad adjustment of the current intensity of the Pololu cf. https://www.pololu.com/product/2133/faqs and https://youtu.be/89BHS9hfSUk,  
- It can also come from faults in the power supply,  
- Or a problem with the connection of the stepper motors, if all the motors have the same problem, it is rather unlikely,  
- It doesn't look like a mechanical fault, but personally I would do a test with a dismantled motor with nothing engaged on the axle,  
- I am thinking more of a Hardware problem, but to remove the doubt, I would do a test with another firmware such as Marlin for example to check if the problem is software or hardware,  
- Finally, since I have several Arduino & RAMPS boards (they are cheapy :smiley:), I would test if the problem occurs on other hardware...  
  
@++;  
Gauthier.
