### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by victor999** [fra589/grbl-Mega-5X#175]
First of all I want to thank you all for this excellent and very useful project.
I designed a PCB for this project and I want to share it - free. I am running CNC with dual X axis and everything works. The PCB designed for XYZXAB configuration with limit switches, so there are changes in config as well. What is the best way to share it? 

I want to share schematic and board files, created in Eagle. My board works with external drivers, like TB6600

**Comment by jonotaegi** [comment]
Hi @victor999,

I am really interested in your Eagle design and config files. I'm building a CNC machine very similar to yours with a dual axis (Y in my case) with limit switches and external TB6600 drivers.

Can you share your files in a GitHub repository?

Thanks!

**Comment by victor999** [comment]
I hope it's OK, I posting a link to my repository
https://github.com/victor999/grbl-mega-board

**Comment by jonotaegi** [comment]
Thanks!

**Comment by fra589** [comment]
Hi @victor999,  
  
Currently, I am reorganizing the code in order to clean the old 3 axis only code, as well as all the old specific configurations from the old Grbl on Arduino Uno.  
After that, it should be easy to set options for specific cards or machines by providing a specific config file and just add a `#define ` statement to point to this file.  
  
@++;  
Gauthier.
