### ISSUE TITLE
I've tried everything..  I can't get any Mega with GRBL 5x or 4 Working?

### ISSUE THREAD

**Issue by OptimusPrimer1** [fra589/grbl-Mega-5X#196]
I've tried everything..  I can't get any Mega with GRBL 5x or 4 Working?  PULLING my hair out Please any help would be amazing.  

1. Libraries won't load correctly.  I've tried everything.  No, how to's or any how-to videos on any of these.  This is super depressing because of how amazing the software is.  

2. I can't get this to boot or run at all

3.  Will the Universal Gcode sender allow me to use that?

I'm running a windows 7 that installed grbl to a uno already but won't install any other grbl versions on any other arduino.  My business is shut down for 2 months already with customers waiting for orders.. I'm losing it... I've tried everything.

Im about to go out of business waiting for this to work.

I even bought a new win 10 desktop.... SAME issue uploading mega with grbl... or uno.. NO luck, cables, Even using geniuine arduino uno and mega

Please I don't understand why this is so difficult?  

Thank you so much!

**Comment by fra589** [comment]
Hi @OptimusPrimer1,  
  
I'm assuming you are using the procedure to compile grbl-Mega-5X with Arduino IDE described in the wiki here: https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X

If you had already installed another version of grbl on another card, it is likely that this old version conflicts with the new 5X version you are trying to install. it's a common mistake. To correct this, you must absolutely delete all previous versions of grbl from the Arduino librarys directorys.
see https://www.arduino.cc/en/guide/libraries for more information about library management.

If you have other problems than this, I need more information to help you:
- Do you have the last version that I published? (it dates from May 5, 2021)
- what parameters have you adjusted in config.h, cpu_maps.h, or any other modification in another file?
- what are the error messages that you get?
- etc.

@ ++;
Gauthier.

**Comment by OptimusPrimer1** [comment]
> 
> 
> Hi @OptimusPrimer1,
> 
> I'm assuming you are using the procedure to compile grbl-Mega-5X with Arduino IDE described in the wiki here: https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X
> 
> If you had already installed another version of grbl on another card, it is likely that this old version conflicts with the new 5X version you are trying to install. it's a common mistake. To correct this, you must absolutely delete all previous versions of grbl from the Arduino librarys directorys.
> see https://www.arduino.cc/en/guide/libraries for more information about library management.
> 
> If you have other problems than this, I need more information to help you:
> 
>     * Do you have the last version that I published? (it dates from May 5, 2021)
> 
>     * what parameters have you adjusted in config.h, cpu_maps.h, or any other modification in another file?
> 
>     * what are the error messages that you get?
> 
>     * etc.
> 
> 
> @ ++;
> Gauthier.
Thank you I managed to do it. I had to delete all other grbl libraries, and finally got it!   Thank you so much!  The only problem is that when I open UGS and try to run a file,
1. Error while starting file stream??
2 . It also starts in alarm mode?
3. Does UGS support 4 or 5 axis?  
4. IM using a mega, I just wanted to confirm the pins from a tutorial video, told me to hook these to be tb6600 drivers?
x STEP =A0,  DIR= A1
y STEP = A6, DIR= A7 
z STEP =D46, DIR= D47

rotary A: STEP = D26, Dir=28
rotary B: STEP = D36, Dir=34

Is this correct while using Tb6600?

Thank you so much!  You are so brilliant, creating a 5 axis Program Like this! GENIUS!

**Comment by fra589** [comment]
Hi,  
  
- For standard pinout definition in grbl-Mega-5X, by searching a little, you could have found the wiki page: https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout  
  
- I don't use UGS, I have my own sender cn5X++: https://github.com/fra589/cn5X  
For your UGS questions, ask to UGS Github's or Google it, you will find easily: https://github.com/winder/Universal-G-Code-Sender/issues/1068  
  
- The Alarm status in normal when powering grbl:
```
// If homing is enabled, homing init lock sets Grbl into an alarm state upon power up. This forces
// the user to perform the homing cycle (or override the locks) before doing anything else. This is
// mainly a safety feature to remind the user to home, since position is unknown to Grbl.
```
To clear the alarm, run the homing cycle by issuing the $H command, or if you know what you do, clear the flag with the $X command (https://github.com/fra589/grbl-Mega-5X/wiki/Grbl-Commands).
  
@++;  
Gauthier.

**Comment by OptimusPrimer1** [comment]
Thank you so much!

1. I just downloaded  cn5x.  I have no idea how to load it?  DO I need to know how to program command lines? 
I click the Setup.py   It went through and closed in a millisecond.  Not sure if it ran.  I have pycharm as well.  

2. Do I NEED ramps 1.4?   DO they make drivers that will fit my 4 axis 6090 nema 23's?  Is there a way to use the TB6600's like I have in the past with grbl uno? I don't want to blow a ramps board, using 3 + amps continuous. 
 
 UGS forum hasn't gotten to my question yet, about the file stream problem.  I have no way of seeing it run right now,  2 different cpus said the same issue?  

 3.  DOES the MEGA require a proper library to run ugs with grbl, or do you only need that when uploading to mega?  Do you think I could by missing a file causing this on both windows CPUs.  I wonder if this is an avg anti-virus issue?  
  Would this work on Pi or jetson nano?  What would you recommend? 
 Any Ideas?  
 
 I can't thank you enough!  
 
 -Andrew

**Comment by fra589** [comment]
Learn to search : www.google.com
and Learn to read!
https://github.com/fra589/cn5X/wiki/Install-cn5X-on-Windows

**Comment by OptimusPrimer1** [comment]
> Learn to search : [www.google.com](http://www.google.com)

> and Learn to read!

> https://github.com/fra589/cn5X/wiki/Install-cn5X-on-Windows


Have you searched these issues for grbl 5x on google?   Nothing comes up for my questions, and I did ask nicely.


What I can't find on google, I will Have to ask.  There is no hardware Diagram for a (mega5x Newbie) to a tb6600?
  
Honestly, it's been a week still no luck.  I've tried everything still can't get this running? 

I don't want to lose hope on this it's such an awesome platform.  I don't want to run mach 3.


I understand you're tired of dealing with these issues.  Which is fair... Lol But at this point, So arent I.   I didn't buy a cnc to learn how to work on a cnc.   I want to make stuff asap.  My business relies on that machine running.   Can't tell you How much time was spent searching google, when I could have been running my machine for customers.  As much time as you spend coding/ following up maybe you could have a video guide, so all of us can enjoy your work sooner?  Thank you!  You are a Legend!

  
  Grbl super easy worked amazing.  But Mega There is very little info on it.  Video wise for anyone that doesn't have a master's in coding. 

C5x is awesome!   Should just be able to jog like UGS, AFTER double clicking the E stop?  IS there any procedure that Im missing not allowing me to run at all.  That still could be mostly a wiring issue.  

I know Its only asking for Dir and Step from the arduino mega?   should be able to use my tb6600's (pulses not steps) right?  OR am forced to use ramps 1.4 with my nema 23's at 24v on my 4 axis 6090?

 I can' t thank you enough!  When we do figure this out you bet I'll make some tutorials for others like me.  
 
 I did do some stuff at mit, so not a complete noob.   I'm at a brick wall.   Thank you again!

**Comment by OptimusPrimer1** [comment]
It would be really cool to have a 4x Filament winding version!  DAMN!  Would that be out of the question lol?

**Comment by fra589** [comment]
Hi @OptimusPrimer1,  
  
You wrote:
> I didn't buy a cnc to learn how to work on a cnc. I want to make stuff asap.
But actually, you are trying to build a CNC milling machine system. This is a trade in its own right which is not that of just using a CNC milling machine.
It requires certain skills that you need to do: either you take the time to learn them, or pay someone competent to do it for you.
Learning takes time, if you are not ready for it, buy a machine ready for use. 
  
When I did this learning path which allowed me to build my own CNC milling machine (I did it because I did not have the financial means to buy one) and to create grbl-Mega-5X . What has always guided me in my research for information is to tell myself that I was not the first to have had this problem and to ask this question. So, looking for similar questions already asked, I almost always found over 99% of the answer. 
  
But if I chose to give back to the community what I added to Grbl to create grbl-Mega-5X, it is because I think that information sharing should be free and open because knowledge should remain free and universal. So I'm going to bring you some answers to your questions, but I'm not going to build your machine for free. 
  
---

Have you read the whole Grbl documentation on the wiki: https://github.com/fra589/grbl-Mega-5X/wiki ?  
Looking closely, I found this title: grbl Mega 5X pinout 
![image](https://user-images.githubusercontent.com/19529154/118607127-83523380-b7b8-11eb-8761-f7ba8ba069c2.png)
  
Clickin on it, I saw:  
![image](https://user-images.githubusercontent.com/19529154/118607401-d1ffcd80-b7b8-11eb-91f4-66cae07293f9.png)
where you can see all the step pulse pins, direction pins and enable/disable pins for all motors up to 6 axes.
  
As I xrote grbl-Mega-5X for RAMPS for simplify his use, on the same wiki page, you will find a link for the RAMPS hardware diagram picture: http://reprap.org/mediawiki/images/c/ca/Arduinomega1-4connectors.png
![image](https://user-images.githubusercontent.com/19529154/118608259-cbbe2100-b7b9-11eb-85c4-1ad6e21cd637.png)
On this picture, the arduino port name is writed for all pins:

You can also search Google for "ramps 1.4 pin assignment": https://www.google.com/search?client=firefox-b-d&q=ramps+1.4+pin+assignment

You will find many picture links like this one:
https://osoyoo.com/2016/07/03/reprap-3d-printer-circuit-connection-graph/
Where it's possible to  see and understand where ans how the steppers conexion are made from the Arduino card to the motor through the RAMPS card.

---

On the grbl-Mega-5X wiki, I also write this page:
https://github.com/fra589/grbl-Mega-5X/wiki/Pinout-mapping-in-cpu_map.h

Where I explain how the mapping is made in the cpu-map.h file of grbl-Mega-5X code.

---

You wrote:
> I understand you're tired of dealing with these issues. Which is fair...
But have you searched in old issues of grbl-Mega-5X?

Googling for "grbl mega 5x pinout mapping": https://www.google.com/search?q=grbl+mega+5x+pinout+mapping
also find old issues which have aleready asked the sams question:
[Complete connection pin #5](https://github.com/fra589/grbl-Mega-5X/issues/5)
  
@++;
Gauthier.
P.S. I don't understand your last comment:
> It would be really cool to have a 4x Filament winding version! DAMN! Would that be out of the question lol?

**Comment by OptimusPrimer1** [comment]
Honestly I, just like the rest of the world want to thank you!  

I am so blown away that people like you!  It's unbelievably inspiring just being a few years into python and coding!

You are SUPERMAN of the Engineering/ Maker world.  Sacrificed you're time and effort writing new code and Helping people like me!  

You changed the game for people that want to LEARN and Create.  THANK you for helping the maker community!  You've inspired me for a lifetime with these programs!

https://youtu.be/MxvUU7Ig1yI?t=27
Filament winding is the future for rockets, bikes, race car frames and the list keeps going! 

This allows makers to make Carbon Fiber or any other fiber, for 85%- 90% LESS money! This is stuff nasa uses.  But we don't have anything open source for the rest of us!

X winder is incredible, and I was wondering, would this be doable, by creating a couple of New tool paths?

I was told that you can use the Fusion 360 threading but, WITHOUT Xwinder, you can't customize how are where the CF is laid.  

There is a huge field emerging.  It also helps because it's saving SO MUCH LABOR and time.  

IS a way to modify this in?  Or use the existing software this way??

WATCH one of these on a 5 axis filament winder...   

Gauthier thank you so much once again!  You have helped SO many people!

**Comment by MrDeadpool05** [comment]
i am stuck help me ...........
i am making 5 axis cnc milling machine
by using arduino mega 2560 +1.4 ramps board 
i uploaded frimware but the E0,E1 is not giving output as Axis A and B but when i am switching it in 4 axis in grbl foam cutter then it gives E0 as Axis U so .... 
my problem is that i my board E0 and E1 which is not as Axis A and B ...... how and what changes i have to make in frimware to get This E0 and E1 as Output Axis A and B.......

>>>first off all i have to make changes in c++ files and header files then...
>>>second how i have to compile it in one single .ino file from bunches of c++ and header files of frimware 

Atleast help me out from my second problem because i don,t know how to make firmware for my machine into single .ino files to upload it in my machines...................
please if somebody knows kindly help me to make it solved............

**Comment by RaphaelDives** [comment]
Hey @MrDeadpool05 
I really don’t want to be rude, but……. https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X

Since the Arduino IDE is just used as an uploading tool, I’d say it’s  not possible to get everything in one project… I would go for a prepared Hex file or something like that. 😉

For the rest, I think you should take a closer look how to configure grbl. (Wiki!) And give a little bit more informations… like the $$ output as a start…

Cheers,
Raphael
