### ISSUE TITLE
avrdude: stk500v2_ReceiveMessage(): timeout

### ISSUE THREAD

**Issue by arlimbad222** [fra589/grbl-Mega-5X#219]
Hello forks 
I am using a clone Arduino board for mega 5x and it's running well for me, I almost run my machine every day about 8 hours no issues in last three Month's  but today I change 2 boards and I face the same issue I just upload a code machine works for a couple of minutes then it disconnects automatically and when i try to upload simple blink sketch to my mega 2560 arduino ide gives this error (avrdude: stk500v2_ReceiveMessage(): timeout) , is there any hardware errors in my board because whenever i change arduino  it works for a couple of minutes.

is there any solution for this error.

**Comment by fra589** [comment]
Hi @arlimbad222 

Are you on Linux or Windows ? Is your boards are chineses clones or Arduino officials ?

Many link for this error on Google like this one:
https://stackoverflow.com/questions/19645441/avrdude-stk500v2-receivemessage-timeout

This is mainly due to a hardware problem...

 You can try to reset fuses and flash manually with those commands:
(these are the commands i use on my linux system)
avrdude -D -v -c avrisp2 -P /dev/ttyUSB0 -p atmega2560 -B 10 -F -U hfuse:w:0xd2:m -U lfuse:w:0xff:m
avrdude -D -v -c avrisp2 -P /dev/ttyUSB0 -p atmega2560 -B 10 -F -U flash:w:grbl.hex:i

replace the -P (/dev/ttyUSB0) with the com port where your board is connected and "grbl.hex" with the hex file name of your compiled program.

@++;
Gauthier.

**Comment by arlimbad222** [comment]
hi @fra589 

I am using windows and Arduino ide to upload the sketch 
I am using Chinese board not an original one I have 3 boards and all board has the same error, (avrdude: stk500v2_ReceiveMessage(): timeout) , I am not programming or coding guy can you please explain more about fuses and how can I find is it a hardware fault or a bootloader problems , I am pretty sure this is hardware fault because whenever I replace Arduino it will work nicely for a couple of hours but I can not find what happened after when I connect Arduino to Pc and open device manager it will show board is connected so I think power regular is not an issue, because it will connect to the computer properly , but when I open serial monitor and type $$ nothing happens,

I am stuck here please help me if possible.

**Comment by arlimbad222** [comment]
Hi @fra589 

Issue solved I just remove all the cables and power off Arduino leave it for a day and wait for discharge all the capacitors and it's working trick for me .

Thanks for support.
