### ISSUE TITLE
Dual Y-Axis Motors (One is working where other is not)

### ISSUE THREAD

**Issue by rehanzfr-zz** [fra589/grbl-Mega-5X#271]
I am new with grbl. I am using mks gen l v2.1 board. This board with marlin is perfectly fine with dual y axis motors. However, I want to use grbl-mega-5x. In this I could not get an idea that how we can run dual y-Axis motors. At this time, the 2nd motor is attached to E1 pins. Please guide.

**Comment by rehanzfr-zz** [comment]
Ok I thing it is resolved: For new comers, here are the steps:

Suppose you have RAMPS board or MKS GEN L V2.1 and you want to use dual Y-Axis motors, single X and single Z axis motors.  If your 2nd Y motor is attached to E1 or 5th axis then perform the following steps. 

1- Open config.h file and change the following code:

`//----------------------------------------------------------------------

// Axis definitions :

//----------------------------------------------------------------------

// IMPORTANT: When changing the axis definitions (axis numbers N_AXIS, 

// linears axis number N_AXIS_LINEAR or axes names AXIS_*_NAME, 

// don't forget to issue the reset factory defaults Grbl command: $RST=*

// if you forget the $RST=* command after change, Grbl may have 

// unpredictable behavior!

//----------------------------------------------------------------------

#define N_AXIS 5        // Number of axes (3 to 6)

#define N_AXIS_LINEAR 3 // Number of linears axis, must be <= N_AXIS

// Axis indexing and names

#define AXIS_1 0        // Axis indexing value. Must start with 0 and be continuous.

#define AXIS_1_NAME 'X' // Axis names must be in X, Y, Z, A, B, C, U, V, W, D, E & H.

#define AXIS_2 1

#define AXIS_2_NAME 'Y'

#define AXIS_3 2

#define AXIS_3_NAME 'Z'

#if N_AXIS <3

  #error "N_AXIS must be >= 3. N_AXIS < 3 is not implemented."

#endif

#if N_AXIS > 3

  #define AXIS_4 3

  #define AXIS_4_NAME 'A' // Letter of axis number 4

#endif

#if N_AXIS > 4

  #define AXIS_5 4

  #define AXIS_5_NAME 'Y' // Letter of axis number 5

#endif

#if N_AXIS > 5

  #define AXIS_6 5

  #define AXIS_6_NAME 'C' // Letter of axis number 6

#endif

#if N_AXIS > 6

  #error "N_AXIS must be <= 6. N_AXIS > 6 is not implemented."

#endif`

Here you can see that I have changed the code '#define N_AXIS 5'  and on 5th axis my second motor is attached, for which I changed the line like this ' #define AXIS_5_NAME 'Y' // Letter of axis number 5'.

Moreover,  in homing section of the same file. I changed like this:

`#elif N_AXIS == 5 // 5 axis : homing

  #define HOMING_CYCLE_0 (1<<AXIS_3) // Home Z axis first to clear workspace.

  #define HOMING_CYCLE_1 (1<<AXIS_1)    // OPTIONAL: uncomment to move X,Y at the same time.

  #define HOMING_CYCLE_2 ((1<<AXIS_2)|(1<<AXIS_5)) // Home Y axis`

In this way, first homing cycle 'HOMING_CYCLE_0' will process Z axis first, after it will home X axis and later it will run both y motors for homing on Y axis.

**Comment by RaphaelDives** [comment]
Hello @rehanzfr,
congrats that you finally made it to grbl-mega-5x. ;)

Since this project is build for the RAMPS Board - I'm not shure if you can use it out of the box - although it should be possible for shure... :)

The first thing would be: https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X

Second: cloning of axes is done at [config.h](https://github.com/fra589/grbl-Mega-5X/blob/edge/grbl/config.h) (right at the beginning), all the stuff you need to know is there in the comments!

As you can find here: https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout#grbl-mega-5x-pinout-on-the-ramps-14 the E1 is defined for the 4th axis (B). So if you have no use for the A axis, I would recommend to use the E0 port instead (I don'd think its possible to use axis 1,2,3 and 5). Of course you could also clone to both E Ports if you don't need them, or you can change the output for the 4th axis in the [cpu_map.h](https://github.com/fra589/grbl-Mega-5X/blob/edge/grbl/cpu_map.h) you will find it also at the beginning. Here is also the place to check wether the outputs are correct for your MKS board! :)

So, if you run into problems, your welcome to report!!

Cheers
Raphael

PS: The question about cloning axis is one of the most asked questions here, by the way... some searching in issues would have done the job as well. But hey I'm a nice person today... :D

**Comment by RaphaelDives** [comment]
Damn, to slow... but at least you found it yourself! 😃 
I think you are on the right way, although imho it would be cleaner to use only 4 axis (instead of 5), in the case you don't need the A axis... (but I don't know about your setup...)

Don't forget the correct configuration for the 5th axis: $101=$104, $111=$114 and so on...
Good luck! :)

**Comment by rehanzfr-zz** [comment]
Thank you very much.

**Comment by fra589** [comment]
Hi @rehanzfr,  
  
I'm glad that you found by yourself, but you may have little problems with it...
With your need to have 3 axis with cloned Y, this mean that there will be 4 linears axis.
In your solution, there is also the A axis which is a rotational axis.
So, the axis number definition should be :
```
#define N_AXIS 5        // Number of axes (3 to 6)
#define N_AXIS_LINEAR 4 // Number of linear axes, must be <= N_AXIS
```

The N_AXIS_LINEAR is internally used to know axes which need the millimeters to inch conversion for G20/G21 modes... With your solution, may be you will have problems if you need to work inches.

But warning ! The linear axes numbers must appears before rotational axes numbers. So, you have 2 solutions for your configuration:
- Connect your Y cloned axis to E0 ans the A axis to E1 (hardware change),
- Invert the axes 4 and 5 definitions in the cpu_map.h file (software change),

And define the axis name like this:
```
#define AXIS_1_NAME 'X'
#define AXIS_2_NAME 'Y'
#define AXIS_3_NAME 'Z'
#define AXIS_4_NAME 'Y'
#define AXIS_5_NAME 'A'
```

@++;  
Gauthier.

**Comment by rehanzfr-zz** [comment]
Yes, you are right. I had the problems even after what I defined above. I will try the new configurations you suggested and will report it back. Thank you very much.
