### ISSUE TITLE
Changing x-max (limit) pin as a-min (limit) pin

### ISSUE THREAD

**Issue by futurau** [fra589/grbl-Mega-5X#272]
Hİ
I am not using max limit pins.
I want to use x-max (limit) pin as a-min (limit) pin,
and y-max (limit) pin as b-min (limit) pin.
Any help will be grateful.

**Comment by fra589** [comment]
Hello @futurau,  
  
The documentation about remapping Grbl IO pins is in the Wiki:  
https://github.com/fra589/grbl-Mega-5X/wiki/Pinout-mapping-in-cpu_map.h  
  
@++;  
Gauthier.

**Comment by ariefadha** [comment]
In Wiki only shows how to remapping the pin, what should I do if I want to discard/delete x-max limit pin? because the x-max limit pin already used by a-min limit, and I don't need grbl to use x-max limit in software.

So a-min (limit) pin move to x-max (limit) pin.
And delete x-max defined by grbl. 

Should I comment out #define port and bit x-max?

**Comment by RaphaelDives** [comment]
I would set the port and pin of x-Max to the same as the x-min.
Grbl defines if it is looking for max or min itself.
Or of course you can set it to any unused pin if there are any…
Cheers!

**Comment by fra589** [comment]
Hi @ariefadha,  
  
When Grbl needs to use a limit (for homing or when hardware limits are used), it simply analyzes whether a limit switch on the concerned axis is triggered (it also doesn't differentiate between min and max switches, this is not useful because this depends on the direction of movement).  
  
If you don't use the X-max limit pin, Grbl won't use it either. So you can leave it set, and define and use it for another limit.  
  
@++;  
Gauthier.
