### ISSUE TITLE
Need clarity on homing. 

### ISSUE THREAD

**Issue by whatwouldiando** [fra589/grbl-Mega-5X#291]
I read in #106 that if I use $5=1 I would need to short all unused limit pins to ground. (As they will all be operating on NC mode, expecting to read low to be considered not actively tripped) Also several times it is recommended to not use the INVERT_MAX_LIMIT_PIN_MASK or the INVERT_MIN_LIMIT_PIN_MASK unless I were to have a mixture of NC and NO switches. So this begs (to me at least) the question:

Why can I not just leave $5=0 and implement 
#define INVERT_MAX_LIMIT_PIN_MASK ((1<<AXIS_1) | (1<<AXIS_2) | (1<<AXIS_3) | (1<<AXIS_4) | (1<<AXIS_5)) 
therefore leaving unused pins alone and not needing to be shorted to ground?

Perhaps I am missing something about the use of the MIN limit pins and homing. I mean I for sure understand the concept of how its all supposed to work, but do the MIN limit pins serve a function if there is nothing connected to them when homing is happening and homing directions are not inverted? My setup has only one limit switch at each of 5 axes (2 clones, y and z) and I have applied a direction invert mask ($3=22) to get each axis moving toward the limits when jogged in the + direction by the controller. Does this direction mask make GRBL correctly interpret the direction for homing in the same direction the axis think is now + without needing to apply a homing direction mask or inversion? or does a similar mask need to be applied for homing? It seems to me I only want a homing direction mask if I want them to home to the - direction but do not want that to be considered the max. 

I have been pouring through the forums and this is still confounding me. I finally have everything moving properly in correct scale and have been able to successfully adjust max speed and accelerations, so homing is all I really have left to get through. Currently I have my cloned z axis moving by itself, all the others acting like they are being triggered right away. The switches seem to be throwing the alarms just fine during setup tests when I trigger them manually, I may be getting some interference from the motors when they try to initiate movement, since the clone z is farther away and has more wire to it perhaps the noise dissipates before the pin can register it? I'm really not sure about all that, I need to get some capacitors to make a low pass filter. But I thought noise should be less of a problem on NC circuits? They are grounded after all. Still new to this and learning as I go, but I want to be sure I'm not missing something in my firmware setup. Any help is much appreciated.

**Comment by fra589** [comment]
Hi @whatwouldiando,  
  
> Also several times it is recommended to not use the INVERT_MAX_LIMIT_PIN_MASK or the INVERT_MIN_LIMIT_PIN_MASK

This is mainly due to the fact that before version 1.1r (March 20, 2021), there was a bug in limit.c which caused the use of INVERT_<MAX|MIN>_LIMIT_PIN_MASK masks to not work correctly.
Since version 1.1r, I haven't had any problems reported regarding their use. So you can leave $5 = 0 and implement
#define INVERT_MAX_LIMIT_PIN_MASK & INVERT_MIN_LIMIT_PIN_MASK.
From a code optimization point of view, the use of limit switch inversion masks adds 2 lines of code to the limit processing algorithm, which adds a few cycles to the processing. This has no particular influence on the performance of grbl, provided you do not enable the use of hardware limits.  
  
The processing of the MIN and MAX limit switches is due to the use of the RAMPS card which has all the MIN and MAX limit connections. This allows Grbl to be used on 3D printer type hardware which are usually wired with the min limit switches.
In fact, the MIN and MAX limit switches have no difference within the code. When homing an axis, if one of the 2 switches is triggered, Grbl will consider the limit reached in the direction of current movement.
The mask $3 is used so that the axes move in the right direction, towards the max for a positive movement and the min for a negative movement.
To choose homing direction, in min or max direction, use the homing inversion mask, parameter $23 ([Grbl-Configuration#23---homing-dir-invert-mask](https://github.com/fra589/grbl-Mega-5X/wiki/Grbl-Configuration#23---homing-dir-invert-mask)).
By default, a milling machine uses the limits of the max side, this makes it possible to free up the workspace as well as possible, which frees up the space and makes it possible to keep the part to be machined (or its fastening system) in place on the work table.  
  
@++;  
Gauthier.

**Comment by whatwouldiando** [comment]
"This has no particular influence on the performance of grbl, provided you do not enable the use of hardware limits."

Maybe I am misunderstanding what enable hardware limits does? I thought that meant the limit switches?
Or are you meaning with them disabled it simply won't slow down grbls processing?

Just so I am clear, to have homing cycles to the + direction, my direction mask ($3) determines which direction that is on the axes (therefore no homing direction mask required, $23), $21=1 (hard limits enabled) is used, and I can use either $5=1 with NC switches and unused pins shorted to ground (MIN_LIMIT_PINs since I do not have those) OR $5=0 and #define INVERT_MAX_LIMIT_PIN_MASK (all axes used with Limit pins on max end). Do I have this right? If so my problem is probably noise from the motors on my input signal lines.

**Comment by whatwouldiando** [comment]
> This has no particular influence on the performance of grbl, provided you do not enable the use of hardware limits.
> 
> Maybe I am misunderstanding what enable hardware limits does? I thought that meant the limit switches?

**Comment by whatwouldiando** [comment]
Apparently my understanding is correct, after installing RC low pass filter on my limit switch input lines I successfully performed a full homing sequence. My only question now is... Is there a way to set a custom pulloff for a cloned axis after homing? I know marlin has this feature for auto squaring in the case a imperfect builds. I don't yet know for sure if my stop blocks that trigger the limits are square with the gantry. Planning on doing some more tests tonight to see how close things are.

**Comment by fra589** [comment]
Hi @whatwouldiando,  
  
The autosquaring parameters functionality is in the TODO list...  
  
@++;  
Gauthier.

**Comment by whatwouldiando** [comment]
I can overcome this temporarily with some shims on the stop blocks, Marlin uses M666 i believe, I am starting to get comfortable with bitwise operators and the style of C that grbl is written in. With some more understanding of the core mechanics perhaps soon I can help develop the codebase more on this with you.

**Comment by whatwouldiando** [comment]
Found a fork of this that looks like they may have implemented auto squaring. Check out Enducross/Grbl_MPCNC_Autosquare.. maybe you can merge some from that.

**Comment by fra589** [comment]
Hi @whatwouldiando,  
  
The Enducross/Grbl_MPCNC_Autosquare fork doesn't implement software auto squaring...  
  
It's just a special configuration which permit to do a mechanical squaring by adjusting the limits switch position of the 2 limit switches of cloned axes.
You can do it by yourself in the original grbl-Mega-5X simply with editing config.h.  
For example, if your axes definition is:

```
#define N_AXIS = 5
#define N_AXIS_LINEAR 4
#define AXIS_1_NAME 'X'
#define AXIS_2_NAME 'Y'
#define AXIS_3_NAME 'Z'
#define AXIS_4_NAME 'Y'
#define AXIS_5_NAME 'A'
```

And llimits switch are on the normal "max" side, with default pinout of grbl-Mega-5X, you need to connect limit switches on Xmax (D2), Zmax (D19), both Ymax (D15 & D40), and optioaly A+ (D59).  

Then, you need to make the homing config in the `#elif N_AXIS == 5` section (line 247+ in config.h):

```
#elif N_AXIS == 5 // 5 axis : homing
  #define HOMING_CYCLE_0 (1<<AXIS_3) // Home Z axis first to clear workspace.
  #define HOMING_CYCLE_1 ((1<<AXIS_1) // home Xaxis.
  #define HOMING_CYCLE_2 (1<<AXIS_2)|(1<<AXIS_4) // Home Y axis and its clone simultanously.
  #define HOMING_CYCLE_3 (1<<AXIS_5) // Home 5th axis (A)
```

Then, by adjusting the 2 Y switches position, you will be able to do the squaring of your machin.  

The logical "Autosquare" feature which is in the TODO list will consist by adding home offset parameters for each axis, so, it will be not necessary to change the mechanical position of the limits switches.

@++;
Gauthier.  
P.S. Don't forget to issue the `$RST=*` command to reset the Grbl's flash when changing the axes definition.

**Comment by fra589** [comment]
No news from near a month... Issue closed.
