### ISSUE TITLE
Cannot control with UGS or Openbuild control software

### ISSUE THREAD

**Issue by Zjokkeh** [fra589/grbl-Mega-5X#334]
I intstalled de mega 5x grbl on my arduino mega. When I look at it in the serial monitor it looks fine to me. If I would like to control the mega with software like UGS or Openbuild, they are not able to connect to the mega. Openbuild even says that there is unkown firmware on the mega. I am I doing something wrong or is this because of the grbl version?

**Comment by fra589** [comment]
Hi @Zjokkeh,  
  
Since I added several features and made many upgrade to the original grbl-mega software, the Grbl version announced during grbl-Mega-5X initialization is (currently) "Grbl 1.2h".
Many of Grbl senders softwares are stuck at version 1.1 (which is pretty stupid in my opinion) and can't imagine that Grbl can still evolve :-(.  
  
You can try to change the version string in the grbl.h file:
`#define GRBL_VERSION "1.1g"`
If that solves your problem, dont hesitate to open issues for UGS or Openbuild softwares for solving this stupid behavior of their software.  
  
@++;  
Gauthier.

**Comment by Zjokkeh** [comment]
Well,

I am going to give that a try. I must say that when I got frustrated yesterday (whoops) and kept clicking the connect in Openbuilds, it suddenly connected and said that it detected the 1.2h firmware. After that I could control the mega. I just have to keep connect until it detects the firmware. Is this also an openbuilds issue or could it be something hardware related from my side? I was thinking to change the baudrate...

**Comment by Zjokkeh** [comment]
Seem to work now, but only on Openbuilds.
