### ISSUE TITLE
does not display the home status during the home loop

### ISSUE THREAD

**Issue by shura-2** [fra589/grbl-Mega-5X#358]
until the home ($H) loop is executed, the controller does not accept the request (?), but resending the command ($H) successfully fills the buffer

**Comment by fra589** [comment]
Hi @shura-2,  
  
This is the normal behavior... 
Since the homing cycle ask extreme speed cpu reactions, the algorithm have no time to run the protocol_execute_realtime() function. This is this function which run the '?' status report. So, the status report will not be executed during the homing cycle.
The other GCode commands which are not immediate commands are put on hold in the input buffer. This is why, if you send $H, it will be executed at the end of the current cycle.

@++;
Gauthier.
