### ISSUE TITLE
Weird alarm code or resetting when making big movement on Y and V axis

### ISSUE THREAD

**Issue by guillaume55** [fra589/grbl-Mega-5X#57]
Hi, 
First thanks a lot for sharing your work
I've tried to use grbl-Mega-5X on a ramps board but it resets and/or sends a weird alarm code (for example 238, can vary) every time I try a big movement (~>10mm) on Y and V axis including $H. Here is my $$ output 

`[echo: $$]
$0=10
$1=255
$2=0
$3=0
$4=0
$5=0
$6=0
$10=17
$11=0.020
$12=0.002
$13=0
$20=0
$21=1
$22=1
$23=0
$24=500.000
$25=2000.000
$26=250
$27=5.000
$30=1000
$31=0
$32=0
$100=200.000
$101=1600.000
$102=800.000
$103=200.000
$104=1600.000
$105=800.000
$110=2000.000
$111=2000.000
$112=2000.000
$113=2000.000
$114=2000.000
$115=2000.000
$120=20.000
$121=20.000
$122=20.000
$123=20.000
$124=20.000
$125=20.000
$130=200.000
$131=200.000
$132=30.000
$133=200.000
$134=200.000
$135=30.000
ok
`
I've only modified defaults.h, cpu_map.h and config.h (6 linear axis : x, y, z, u, v, w, where w and x are inverted ). None of Y and V (and other axis seems to be defined 2 times)
I can post the modification on these files if needed
I'm not sure if the issue comes from me or belongs to the rest of the code
Thanks a lot
Guillaume

edit : 
All the following results are with unmodified grbl (only eeprom settngs)
I get alarm 2 if I try a movement  with unmodified code (without homing)

if I remove (in eeprom settings) software limits and I modify $101=1600, $111=2000 and $121=20 : 
- (1st try) G0 Y20 (works) G0 Y-50 => V and X starts to move and Y stopped
- (2nd try) G0 Y-10 to Y-100 (ten by ten because the Y axis reached the end of the axis, worked) G0 Y-80 => stops with alarm: 15 (does not exist, alarm 1 + alarm 5?)
- (3rd try) G0 Y20 => door is open (all control pins are connected to +5V directly)
- (4th try) G0 Y30 => seems to have not traveled 30mm but stops, answer ok to commands but don't move

I don't understand with I get different error each time, even with unmodified code. I will try with a new ramps and arduino asap

Edit 2 : 
It seems to work at least for one axis movement after changing electronics AND switching from 1/16th of step to full step. I think much steps to do was in cause. 
Maybe (in config.h) 
ACCELERATION_TICKS_PER_SECOND
BLOCK_BUFFER_SIZE
SEGMENT_BUFFER_SIZE
LINE_BUFFER_SIZE
parameters are involved but i'm not sure
So changing microstepping mode is a way to "hide" the issue but maybe not the better thing to actually solve the issue

**Comment by fra589** [comment]
Hi @guillaume55,  
1) For you to understand the behavior of Grbl, and in particular answer your question on the alarm # 2 that you get when you try a movement before making the reference, I will explain to you the standard behavior of a CNC milling machine. This behavior is implemented on the vast majority of machines, and mainly responds to security concerns.
When you turn on a CNC machine controller, it can not know the position of the different axes. For this, he must perform a homing. In its standard configuration, when Grbl is powered up (or reset), it is placed in Alarm mode, which prevents any movement. If you try a move in this mode, you will get a 9 (G-code lock) error.
This alarm status is released, either by executing the homing, or by sending a $X command. The machine coordinates of all the axes are set to 0 when homing, or considered at 0 whatever their position when unlocked by $X, it is to the user to know where are the axes and do not ask for movement out of bounds or dangerous. This behavior can be disabled in Grbl by setting the parameter $22 (Homing cycle) to 0.
As a general rule, homing is performed on the limit stops (X +, Y +, Z +, ...). This makes it possible to clear the work area as much as possible and thus avoid collisions. By default, the only possible movements after homing are movements with negative machine coordinates. If the option "Soft limits" ($ 20) is active, then you will get an alarm # 2 (Soft limit) if you try an axis motion with a positive value, as well as if you try a movement with a negative value whose absolute value than exceeds the value of the "Max travel" parameter ($ 130 to $ 135) of the axis.
Movements with positive axis values ​​will subsequently be possible only relative to a part repository, which will be at negative coordinates with respect to the machine origin.
By disabling the "Soft limits" option, there is no more alarm generated if the maximum movement is exceeded. That's why after configuring $ 20 = 0, you can make positive movements without having previously defined a coin origin.

2) Warning! When changing the axis configuration in the Grbl source code, it is most of the time necessary to completely reset the eeprom that contains the configuration. for that, it is necessary to send the command `$ RST = *` with each download of a new firmware Grbl in the arduino and to redo the configuration. Personally, I regularly forget to do it, and often, I get totally erratic behavior in these cases ...

3) Given the configuration items that you have posted, it is also possible that you outsource the processing capabilities of your Arduino board. If one makes a quick calculation on the parameters of your Y axis (step / mm and maximum speed), one obtains: 1600 ($101) x 2000 ($111) / 60 = 53.33 kHz. This significantly exceeds the processing speed of Arduino boards which are between 25 and 35 kHz for the pulse of the stepper motors with Grbl.
The G0 commands correspond to movements in fast speed, and therefore, Grbl uses the maximum speed of the axes defined in the configuration. The default configuration of Grbl refers, for X and Y, to a machine using belts and asks for 80 x 9000/60 = 12 kHz pulse frequency at the arduino. Your machine seems to be a screw system, given your "$101" parameter, you either have to reduce the number of steps per mm, or you decrease the maximum speed for it to work.
By using the motors in "full step" mode instead of 1/16, you divide by 16 the number of steps per mm, and thus the frequency of sending the implants to the steppers' drivers and it starts to work, this seems normal to me.
If you want to determine the maximum possible speed of your machine, use gcode commands G1 Y-xxx ... Fxxx by gradually increasing the speed F.
You can also test different acceleration values ​​($120 to $125) to optimize it.
The result depends both on the quality of your electronic components and the mechanical system.
I do not think that the other internal parameters of the Grbl program that you are considering to modify (`ACCELERATION_TICKS_PER_SECOND`, `BLOCK_BUFFER_SIZE`, `SEGMENT_BUFFER_SIZE` & `LINE_BUFFER_SIZE`) will correct your problem...  

@++;  
Gauthier.
