### ISSUE TITLE
Reprap discount smart controller lcd compatiblity

### ISSUE THREAD

**Issue by coilheaddesigns** [fra589/grbl-Mega-5X#61]
Good day.
Is there a way to get lcd compatability for the lcd display from reprap.
Perhaps just basic jog and home and set zero.
With grbl position on the main display.

**Comment by fra589** [comment]
Hi @coilheaddesigns,  
it's not in the pipes to implement a simple LCD display on grbl-Mega-5X as I think it may slow it down too much.  
My [cn5X project](https://github.com/fra589/cn5X) is attended to run on Rasberry PI with touch screen and so, to be a complete solution to drive 3 to 6 axis CNC machine with all it's functionalities. It will use a medium size touch screen, showing all relevant information in real time, and touch buttons and menus to jog and control al the grbl-Mega-5X functionalities.

@++;
Gauthier.

**Comment by coilheaddesigns** [comment]
OK cool no problem than you for the response

**Comment by coilheaddesigns** [comment]
Would it be possible to copy the code from issue #77 to you version or will it be to difficult for someone with beginner coding skills.

I have to start getting into c++ for this hobby of mine😂

**Comment by fra589** [comment]
Hi @coilheaddesigns,  
I think it's not really within the reach of a beginner.  
I have a good programming experience: I worked on the development of CAD software and post-processors since 1993 (I would be retired at the end of this month), and it took me several weeks / months to do the reverse engineering of the grbl original, in order to be able to evolve it to what it became in the 5X version.  
But if you have courage, it will be a great adventure for you to do it.  
@++;
Gauthier.

**Comment by coilheaddesigns** [comment]
Than you for you advice it is much appreciated
