### ISSUE TITLE
Utilising unused pins on 2560

### ISSUE THREAD

**Issue by ghost** [fra589/grbl-Mega-5X#77]
I am currently designing a custom CNC board that has capability for multiple types of limit switch inputs (mechanical & Inductive (+ve and -ve triggered) and was wondering if some of the unused ports / pins on the 2560 can be utilised?

In essence I was curious if you could define two new inputs per current limit switch defined pins 
 that may be something along the lines of (or any other format that you prefer);
x-min_b, x-min_c
x-max_b, x-max_c
y-min-b, y-min_c
y-max_b, y-max_c
z-min-b, z-min_c
z-max_b, z-max_c
a-min-b, a-min_c
a-max_b, a-max_c
b-min-b, b-min_c
b-max_b, b-max_c

I assume there are enough spare pins to do this and hope this is something that is fairly easy to do.

Cheers
George

**Comment by fra589** [comment]
Hello @gxdeange,

Pins definitions for limits switchs are defined in cpu_map.h (line 246 to 305).
Those definitions are used in limits.c and setting.c using the defined macros : `MIN_LIMIT_BIT(i)`, `MIN_LIMIT_DDR(i)`, `MIN_LIMIT_DDR(i)`, `MIN_LIMIT_PIN(i)` and the corresponding macro for MAX_*.

I think it's not so easy to do due to the limitation of the 8 bits architecture. Limit switch definition are used in 8 bits masks and using more than 8 limits switch definitions for all axis will be pretty complicated.  

@++;
Gauthier.
