### ISSUE TITLE
Homing cycle definitions

### ISSUE THREAD

**Issue by rasciodc** [fra589/grbl-Mega-5X#8]
Hello there!

I was trying to change the homing cycle sequence and came accross the following problem: No matter what was the number of axis "N_AXIS" defined in the nuts_bolts.h file, GRBL would always perform the homing cycle as if "N_AXIS" was not defined (i.e it would enter the classic 3 axis homing definition in line 122 of file config.h instead of following the expected code on lines 111 and 116 (4 and 5 axis respectively).

I don't know the "right" way to solve this, since the original GRBL Mega defines N_AXIS on the nuts_bolts file.... But what I did, and it worked, was to move all code between lines 31 and 61 from nuts_bolts.h file to the config.h file, to make sure N_AXIS was correctly defined.

Not sure about that, but, I think this is a modification that would be necessary on original GRBL Mega branch.... I say this because before moving this chunck of code from one file to another, I tried to modify the order in which files were #included in the grbl.h file by including nuts_bolts.h before config.h to have the N_AXIS set before entering the config.h file.....but that threw a bunch of other errors....

Well, I wrote more than I intended to so.... there is that! The homing cycle is not working as is and that was my work around!

Cheers!

**Comment by fra589** [comment]
Hi @rasciodc,

You are right ! Definition of N_AXIS is in a wrong place, it must be in config.h file. I will correct it on the next version (6 axis version) of grbl-Mega-5X...  
In fact, only the 31 to 55 lines of nut_bolts.h must be moved in the config.h file. Line 56 to 61 are for CoreXY.  
In the original version of GRBL, N_AXIS is not used in config.h, since N_AXIS have always the value of 3 :stuck_out_tongue_winking_eye:   so, the original version don't need this update.
  
Many thanks for your return, it permit to me to correct this bug :-)  
  
@++;  
Gauthier.
